spring:
  profiles:
    active: test

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    # 모든 로그의 기본 레벨을 INFO로 설정
    root: INFO
    # 특정 패키지의 로그 레벨을 DEBUG로 설정 (개발 시 유용)
    com.example.myapp: DEBUG
    # 스프링 프레임워크의 로그 레벨을 INFO로 설정 (너무 많은 로그 방지)
    org.springframework.web: INFO
    # 하이버네이트의 SQL 파라미터 로그를 DEBUG로 설정
    org.hibernate.type.descriptor.sql: DEBUG

  # 로그 파일 설정
  file:
    # 로그 파일 이름 지정 (상대 경로 또는 절대 경로 가능)
    # 예: logs/app.log -> 프로젝트 폴더 내 logs 폴더에 app.log 파일 생성
    name: logs/app.log

  # 로그 출력 패턴 설정 (선택 사항)
  pattern:
    # 콘솔에 출력될 로그 형식
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    # 파일에 기록될 로그 형식
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"